config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  concern :commentable do
    resources :comments
  end

  resources :questions, concerns: :commentable, shallow: true do
    resources :answers, concerns: :commentable
  end

  root to: "questions#index"

end

app/models/answer.rb
class Answer < ActiveRecord::Base
	belongs_to :question
	has_many :attachments, as: :attachmentable
	has_many :comments, as: :commentable

	validates :body, presence: true

	accepts_nested_attributes_for :attachments
end

app/models/attachment.rb
class Attachment < ActiveRecord::Base
	belongs_to :attachmentable, polymorphic: true

	mount_uploader :file, FileUploader
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :commentable, polymorphic: true

	validates :body, presence: true
end

app/models/question.rb
class Question < ActiveRecord::Base
	validates :title, :body, presence: true
	has_many :answers
	has_many :attachments, as: :attachmentable
	has_many :comments, as: :commentable
	
	accepts_nested_attributes_for :attachments
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
	before_action :authenticate_user!
	before_action :load_answer, only: :update
	after_action :publish_answer, only: :create

	respond_to :js
	respond_to :json, only: :create

	def create
		@question = Question.find(params[:question_id])
		respond_with(@answer = @question.answers.create(answer_params))
	end

	def update
		@answer.update(answer_params)
		respond_with @answer
	end

	private

	def load_answer
		@answer = Answer.find(params[:id])
		@question = @answer.question
    end

    def publish_answer
    	PrivatePub.publish_to "/questions/#{@question.id}/answers", answer: @answer.to_json
    end

	def answer_params
		params.require(:answer).permit(:body, attachments_attributes: [:file])
	end
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :authenticate_user!
	before_action :load_parent

	respond_to :js

	def create
		respond_with(@comment = @parent.comments.create(comment_params))
	end

	private

	def load_parent
		@parent = Question.find(params[:question_id]) if params[:question_id]
		@parent ||= Answer.find(params[:answer_id])
	end


	def comment_params
		params.require(:comment).permit(:body)
	end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
	before_action :load_question, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!, only: [:new, :create ]
	before_action :build_answer, only: :show

    respond_to :html

	def index
		respond_with(@questions = Question.all)
	end

	def show
		respond_with @question
	end

	def new
		respond_with(@question = Question.new)
	end

	def edit
	end

	def create
		respond_with(@question = Question.create(question_params))
	end

	def update
		@question.update(question_params)
		respond_with @question
	end

	def destroy
		respond_with(@question.destroy)
	end

	private

	def load_question
		@question = Question.find(params[:id])
	end

	def build_answer
		@answer = @question.answers.build
	end

    def question_params
    	params.require(:question).permit(:title, :body, attachments_attributes: [:file])
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/answers/create.js.erb
<% if @answer.errors.present? %>
  <% @answer.errors.full_messages.each do |message| %>
    $('.answer-errors').html('<%= j message %>');
  <% end %>
<% else %>
  $('.new_answer #answer_body').val('');
<% end %>

app/views/answers/update.js.erb
<% if @answer.errors.present? %>
  <% @answer.errors.full_messages.each do |message| %>
    $('.answer-errors').html('<%= j message %>');
  <% end %>
<% else %>
  $('.answers').html('<%= j render 'questions/answers' %>');
  $('.edit-answer-link').click(function(e) {
    e.preventDefault();
    $(this).hide();
    answer_id = $(this).data('answerId');
    $('form#edit-answer-' + answer_id).show();
  });
<% end %>

app/views/comments/_comment.html.slim
p= comment.body

app/views/comments/_list.html.slim
= render parent.comments
=form_for [parent, parent.comments.build], remote: true do |f|
  p
    = f.label :body, 'Comment'
    = f.text_area :body
  p
    = f.submit 'Post comment'

app/views/comments/create.js.erb
var parentSelector = '<%= @parent.is_a?(Question) ? ".question" : "#answer-#{@parent.id}" %>';
$(parentSelector + ' .comments').html('<%= j render "list", parent: @parent %>');

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Qna</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<%= yield %>

</body>
</html>

app/views/questions/_answers.html.slim
- @question.answers.each do |answer|
  - if answer.persisted?
    .answer id="answer-#{answer.id}"
      p= answer.body
      ul
        - answer.attachments.each do |a|
          li= link_to a.file.identifier, a.file.url

      - if user_signed_in?
        p= link_to 'Edit', '', class: 'edit-answer-link', data: { answer_id: answer.id }
        p
          = form_for answer, remote: true, html: { id: "edit-answer-#{answer.id}" } do |f|
            = f.label :body, "Answer"
            = f.text_area :body
            = f.submit 'Save'
        .comments
          = render 'comments/list', parent: answer

app/views/questions/index.html.slim
p= link_to 'Ask question', new_question_path

app/views/questions/new.html.slim
=form_for @question do |f|
  p
    = f.label :title
    = f.text_field :title
  p
    = f.label :body
    = f.text_area :body
  p Attachments:
  p
    = f.fields_for :attachments, @question.attachments.build do |a|
      = a.label :file
      = a.file_field :file

  p = f.submit 'Create'

app/views/questions/show.html.slim
.question
  h1= @question.title
  p= @question.body
  p Attachments:
  ul
    - @question.attachments.each do |a|
      li= link_to a.file.identifier, a.file.url
  .comments
    = render 'comments/list', parent: @question

.answers data={question_id: "#{@question.id}"}
  = render 'answers'

= form_for [@question, @answer], remote: true do |f|
  p
    = f.label :body, 'Your answer'
    .answer-errors
    = f.text_area :body
  p
    = f.fields_for :attachments, @answer.attachments.build do |a|
      = a.label :file
      = a.file_field :file

  p= f.submit 'Create'

= subscribe_to "/questions/#{@question.id}/answers"